// ScrollReveal({ reset: true });
// ScrollReveal().reveal('.navbar', { easing:"ease-in", delay: 100});
// ScrollReveal().reveal('.head', { easing: "ease-in", delay: 100});
// ScrollReveal().reveal('.container-fluid-lg', { easing: "ease-in", delay: 50});
// ScrollReveal().reveal('.nav-outer1', { easing: "ease-in", delay: 50});
// ScrollReveal().reveal('p', { easing: "ease-in", delay:100 });
// ScrollReveal().reveal('.footer', { easing: "ease-in", delay: 100 });
// ScrollReveal().reveal('.call', { easing: "ease-in", delay: 100 });
// ScrollReveal().reveal('.articles', { easing: "ease-in", delay: 100 });
// ScrollReveal().reveal('.fancy', { easing: "ease-in", delay: 100 });
// ScrollReveal().reveal('.ftr', { easing: "ease-in", delay: 100 });
// ScrollReveal().reveal('.principal_section_right', { easing: "ease-in", delay: 150 });
// ScrollReveal().reveal('.principal_section_left', { easing: "ease-in", delay: 150 });
// ScrollReveal().reveal('.principal_bio', { easing: "ease-in", delay:150 });
// ScrollReveal().reveal('.principal_welcome', { easing: "ease-in", delay:150 });
